#!/usr/bin/env bash
# Generated by k8s-ansible-ha from k8s-cp-0 (192.168.56.134).
# The token expires 24h after generation; the certificate key after 2h.
# Both are regenerated automatically by add-worker.yml / add-master.yml,
# so this file is for manual/emergency use only.

# ---- Join a WORKER ----
kubeadm join 192.168.56.100:6443 --token yrgy1o.at640qspzq6ri86h --discovery-token-ca-cert-hash sha256:231017722d1b505abfc3458d9d381f475f08d028f2905eb49c2f5e468eb33149

# ---- Join a CONTROL PLANE ----
kubeadm join 192.168.56.100:6443 --token yrgy1o.at640qspzq6ri86h --discovery-token-ca-cert-hash sha256:231017722d1b505abfc3458d9d381f475f08d028f2905eb49c2f5e468eb33149 --control-plane --certificate-key 573cc82f6458f30fed05185b2b97161e65e4d4e41adcd075f1c5d3893707de9b
